language: go
sudo: false
jobs:
  include:
    - stage: build
      os: linux
      go: 1.12.5
      before_install:
        - go get -t -v ./...      
      before_script:
        - ./go.test.sh
      script:
        - go test -race -coverprofile=coverage.txt -covermode=atomic
      after_success:
        - bash <(curl -s https://codecov.io/bash) 
