language: go
sudo: false
go:
  - 1.8.x
  - tip

before_install:
  - go get -t -v ./...

script:
  - ./go.test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash) -t cc39d0a1-33a3-4e38-91ef-942566752b4a
